
export enum ServiceName {
    listType = 'listtypes',
    listings = 'listings',
    search = 'search', 
    similar = 'similars', 
    category = 'categories', 
    categoryList = 'categoryList', 
    state = 'states',
    product = 'products', 
    account = 'accounts', 
    userAccount = 'useraccounts',
    login = 'login', 
    create = 'create',
    names = 'names', 
    address = 'address',
    cartItems = 'cartitems', 
    orders = 'orders',
    orderItems = 'orderitems',
    id = 'id',
    move = 'move',
    userNotes = 'userNotes',
    userFeedback = 'userFeedback', 
    jwt = "jwt", 
    getClaim = "getclaim", 
    media = "media"
}
